ktor:
    application:
        modules:
            - ru.andvl.chatter.backend.ApplicationKt.module
    deployment:
        port: 8081

#koog:
#  openai:
#    api_key: ${OPENAI_API_KEY:-dummy-key}
#  google:
#    api_key: ${GOOGLE_API_KEY:-dummy}
#  openrouter:
#    api_key: ${OPENROUTER_API_KEY:-dummy}
#  anthropic:
#    api_key: ${ANTHROPIC_API_KEY:-dummy-key}
#  deepseek:
#    api_key: ${DEEPSEEK_API_KEY:-dummy-key}
#  groq:
#    api_key: ${GROQ_API_KEY:-dummy-key}
#  mistral:
#    api_key: ${MISTRAL_API_KEY:-dummy-key}
#  openaichat:
#    api_key: ${OPENAI_API_KEY:-dummy-key}